name: "TypeScript Github Action Template"
description: "A template to create custom GitHub Action with TypeScript/JavaScript."
inputs:
  github-token:
    description: "GitHub token."
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
  post-if: always()
branding:
  icon: "box"
  color: "yellow"
