name: "TypeScript Github Action Template"
description: "A template to create custom GitHub Action with TypeScript/JavaScript."
inputs:
  github-token:
    description: "GitHub token."
    required: false
    default: ${{ github.token }}
  release-type:
    description: "One of the following: major, minor, patch, premajor, preminor, prepatch, prerelease."
    required: false
    default: "patch"
  prerelease:
    description: "Mark the GitHub Release as a pre-release."
    required: false
    default: false
  dry-run:
    description: "Dry run without making changes."
    required: false
    default: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "yellow"
