name: Release

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      prerelease:
        description: "Prerelease"
        required: true
        default: true
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  eslint:
    uses: ./.github/workflows/eslint.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  release:
    name: Release
    needs: [build, test, eslint, codeql]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - uses: ./
        with:
          release-type: ${{ inputs.release-type || "patch" }}
          prerelease: ${{ inputs.prerelease || true }}
          update-shorthand-release: true
