name: Release

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  eslint:
    uses: ./.github/workflows/eslint.yml

  codeql:
    uses: ./.github/workflows/codeql.yml

  release:
    name: Release
    needs: [build, test, eslint, codeql]
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - uses: ./
        with:
          release-type: patch
          prerelease: true
          update-shorthand-release: true
